class LoginPage:
    # Locators for the login page
    USERNAME_FIELD = "is=username"
    PASSWORD_FIELD = "id=password"
    LOGIN_BUTTON = "id=loginButton" 
    POPUP_BUTTON = "id=popupButton"
    ERROR_MESSAGE = "id=errorMessage"
    LOGIN_BUTTON = "id=loginButton"
    LOGOUT_BUTTON = "id=logoutButton"
    USER_NAME_FIELD = "id=username"
    Serial_key = "123456876"
    PASSWORD_FIELD = "741425852"
    USER_NAME_FIELD = "malay"
    LOGIN_BUTTON = "id=loginButton"
    LOGOUT_BUTTON = "id=logoutButton"
    USER_NAME_FIELD = "id=username"
    PASSWORD_FIELD = "id=password"
    LOGIN_BUTTON = "id=loginButton"
    LOGOUT_BUTTON = "id=logoutButton"
